coverage:
  status:
    project:
      default:
        flags:
          - backend
          - frontend
          - frontend-admin
        paths:
          - "!src/kohaku-hub-ui/src/components/repo/RepoViewer.vue"
          - "!src/components/repo/RepoViewer.vue"
