[s3]
public_endpoint = "http://127.0.0.1:29001"
endpoint = "http://127.0.0.1:29001"
access_key = "minioadmin"
secret_key = "minioadmin"
bucket = "hub-storage"
region = "us-east-1"
force_path_style = true

[lakefs]
public_endpoint  = "http://127.0.0.1:28000"
internal_endpoint = "http://127.0.0.1:28000"
access_key = "xxx"
secret_key = "yyy"
repo_namespace = "hf"

[app]
base_url = "http://127.0.0.1:48888"
api_base = "/api"
database_url = "sqlite:///./hub.db"
lfs_threshold_bytes = 10485760 # 10MB
debug_log_payloads = true
