version: "3.9"

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":29000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "29001:9000"    # S3 API
      - "29000:29000"   # Web Console
    volumes:
      - /Iolite/hub-storage/minio-data:/data   # HDD 儲存大檔案
      - /data/hub-meta/minio-data:/root/.minio # SSD 存 metadata

  lakefs:
    image: treeverse/lakefs:latest
    container_name: lakefs
    environment:
      LAKEFS_DATABASE_TYPE: local
      LAKEFS_DATABASE_LOCAL_PATH: /var/lakefs/data/metadata.db
      LAKEFS_BLOCKSTORE_TYPE: s3
      LAKEFS_BLOCKSTORE_S3_ENDPOINT: http://minio:9000
      LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE: "true"
      LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID: minioadmin
      LAKEFS_BLOCKSTORE_S3_CREDENTIALS_SECRET_ACCESS_KEY: minioadmin
      LAKEFS_AUTH_ENCRYPT_SECRET_KEY: "YOUR_SECRET_KEY"
      LAKEFS_LOGGING_FORMAT: text
      LAKEFS_LISTEN_ADDRESS: "0.0.0.0:28000"
    ports:
      - "28000:28000"   # lakeFS Web + API
    user: "${UID}:${GID}" # May be crucial for lakefs/data and cache to work correctly
    depends_on:
      - minio
    volumes:
      ### NOTE: REMEMBER TO ENSURE THE PERMISSIONS OF /data/hub-meta/lakefs-data and /lakefs/data/cache
      ### LakeFS may not be able to access these directories (always check docker logs for errors)
      - /data/hub-meta/lakefs-data:/var/lakefs/data
      - /data/hub-meta/lakefs-cache:/lakefs/data/cache
networks:
  default:
    name: hub-net