[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kohaku-hub"
version = "0.0.1"
description = ""
authors = [
    { name = "Shih-Ying Yeh(KohakuBlueLeaf)", email = "apolloyeh0123@gmail.com" },
]
license = { text = "Apache-2.0" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "httpx",
    "uvicorn",
    "pydantic[email]",
    "toml",
    "peewee",
    "boto3",
    "lakefs-client",
    "psycopg2-binary",
    "pyyaml",
    "bcrypt",
    "questionary",
    "rich",
    "python-multipart",
]
urls = { "Homepage" = "https://kblueleaf.net/Kohaku-Hub" }

[project.optional-dependencies]
dev = [
    "huggingface_hub",
]


[project.scripts]
kohub-cli = "kohub_cli.main:main"

[tool.setuptools]
package-dir = {"" = "src"}