name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Backend API
        - Frontend UI
        - CLI Tool
        - Documentation
        - Docker/Deployment
        - LakeFS Integration
        - S3/Storage
        - Authentication
        - Organizations
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g. Ubuntu 22.04, Windows 11, macOS 14]
        - Python Version: [e.g. 3.10, 3.11]
        - Node.js Version: [e.g. 18.x, 20.x]
        - Docker Version: [e.g. 24.0.0]
        - Deployment: [e.g. Docker, Local Development]
        - Browser (if UI issue): [e.g. Chrome 120, Firefox 121]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Relevant logs or error messages
      placeholder: |
        Paste any relevant logs or error messages here.
        Use docker-compose logs -f hub-api for backend logs.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information that might help
      placeholder: Screenshots, configuration files, related issues, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all requested information
          required: true
        - label: I am using the latest version of KohakuHub
          required: false
