name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea in detail.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're facing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: Describe any alternative approaches you've considered...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Backend API
        - Frontend UI
        - CLI Tool
        - Documentation
        - Docker/Deployment
        - LakeFS Integration
        - S3/Storage
        - Authentication
        - Organizations
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking current work
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case for this feature
      placeholder: |
        Who will benefit from this feature?
        How will it be used?
        What value does it provide?
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Any examples, mockups, or code snippets
      placeholder: |
        Provide examples of how this feature would work,
        including API examples, UI mockups, or code snippets.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information
      placeholder: Links to related projects, similar features in other tools, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have checked the roadmap in CONTRIBUTING.md
          required: true
        - label: I am willing to help implement this feature
          required: false
