name: Question / Help
description: Ask a question or get help
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

        **Note:** For quick answers, consider joining our [Discord](https://discord.gg/xWYrkyvJ2s)!

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What is your question about?
      options:
        - Setup / Installation
        - Configuration
        - API Usage
        - CLI Usage
        - Frontend Development
        - Backend Development
        - Deployment
        - Authentication / Permissions
        - Organizations
        - Performance / Optimization
        - Troubleshooting
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Additional context about your question
      placeholder: |
        What are you trying to accomplish?
        What have you tried so far?
        Any relevant configuration or setup details?

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      placeholder: |
        - OS: [e.g. Ubuntu 22.04]
        - Python Version: [e.g. 3.10]
        - Deployment: [e.g. Docker, Local]

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have checked the documentation
          required: true
        - label: I have searched existing issues
          required: true
